spring.application.name=insuranceAss
# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=insuranceass
spring.data.mongodb.auto-index-creation=true