spring.application.name=insuranceAss
server.port=8080

# Tomcat Windows Temp Fix
server.tomcat.basedir=target/tomcat
server.tomcat.session.persistent=false

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=insuranceass
spring.data.mongodb.auto-index-creation=true